[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.obj.tickets"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "tickets"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.object.tickets"

[build-options]
observabilityIncluded = true
